// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * text field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice = ImageSlice | TextSlice | TextWithImageSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Bottom Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.bottom_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bottom_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Page → Slider*
 */
export interface PageDocumentDataSliderItem {
  /**
   * image field in *Page → Slider*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slider[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * fig field in *Page → Slider*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slider[].fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;
}

type PageDocumentDataSlicesSlice =
  | S7525Slice
  | S3366Slice
  | S404020Slice
  | S5050Slice
  | S25252525Slice
  | FullwidthSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slider field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slider[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slider: prismic.GroupField<Simplify<PageDocumentDataSliderItem>>;

  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * size field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.size
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  size: prismic.RichTextField;

  /**
   * year field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * media field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  media: prismic.RichTextField;

  /**
   * extrainfo field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.extrainfo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  extrainfo: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SelectedProjectDocumentDataSlicesSlice =
  | S3366Slice
  | S404020Slice
  | S5050Slice
  | S7525Slice
  | S25252525Slice
  | FullwidthSlice;

/**
 * Content for Selected Project documents
 */
interface SelectedProjectDocumentData {
  /**
   * Slice Zone field in *Selected Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: selected_project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SelectedProjectDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Selected Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: selected_project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Selected Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: selected_project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Selected Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: selected_project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Selected Project document from Prismic
 *
 * - **API ID**: `selected_project`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SelectedProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SelectedProjectDocumentData>,
    "selected_project",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | HomeDocument
  | PageDocument
  | SelectedProjectDocument
  | SettingsDocument;

/**
 * Primary content in *Fullwidth → Primary*
 */
export interface FullwidthSliceDefaultPrimary {
  /**
   * link field in *Fullwidth → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Fullwidth → Items*
 */
export interface FullwidthSliceDefaultItem {
  /**
   * image field in *Fullwidth → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Fullwidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * year field in *Fullwidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * fig field in *Fullwidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;
}

/**
 * Default variation for Fullwidth Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullwidthSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullwidthSliceDefaultPrimary>,
  Simplify<FullwidthSliceDefaultItem>
>;

/**
 * Primary content in *Fullwidth → Items*
 */
export interface FullwidthSlicePaddingOnTheSidesItem {
  /**
   * image field in *Fullwidth → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Fullwidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * year field in *Fullwidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * fig field in *Fullwidth → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;

  /**
   * link field in *Fullwidth → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: fullwidth.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkToMediaField;
}

/**
 * Padding on the sides variation for Fullwidth Slice
 *
 * - **API ID**: `paddingOnTheSides`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullwidthSlicePaddingOnTheSides = prismic.SharedSliceVariation<
  "paddingOnTheSides",
  Record<string, never>,
  Simplify<FullwidthSlicePaddingOnTheSidesItem>
>;

/**
 * Slice variation for *Fullwidth*
 */
type FullwidthSliceVariation =
  | FullwidthSliceDefault
  | FullwidthSlicePaddingOnTheSides;

/**
 * Fullwidth Shared Slice
 *
 * - **API ID**: `fullwidth`
 * - **Description**: Fullwidth
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullwidthSlice = prismic.SharedSlice<
  "fullwidth",
  FullwidthSliceVariation
>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Tags field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.tags
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tags: prismic.RichTextField;
}

/**
 * Primary content in *Image → Items*
 */
export interface ImageSliceDefaultItem {
  /**
   * Image field in *Image → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Image → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: image.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  Simplify<ImageSliceDefaultItem>
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *S25252525 → Primary*
 */
export interface S25252525SliceDefaultPrimary {
  /**
   * image1 field in *S25252525 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * title1 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * year1 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.year1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year1: prismic.RichTextField;

  /**
   * fig1 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.fig1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig1: prismic.RichTextField;

  /**
   * link1 field in *S25252525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkToMediaField;

  /**
   * image2 field in *S25252525 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * title2 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * year2 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.year2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year2: prismic.RichTextField;

  /**
   * fig2 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.fig2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig2: prismic.RichTextField;

  /**
   * link2 field in *S25252525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkToMediaField;

  /**
   * image3 field in *S25252525 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.image3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;

  /**
   * title3 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.title3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title3: prismic.RichTextField;

  /**
   * year3 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.year3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year3: prismic.RichTextField;

  /**
   * fig3 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.fig3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig3: prismic.RichTextField;

  /**
   * link3 field in *S25252525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.link3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link3: prismic.LinkToMediaField;

  /**
   * image4 field in *S25252525 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.image4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>;

  /**
   * title4 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.title4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title4: prismic.RichTextField;

  /**
   * year4 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.year4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year4: prismic.RichTextField;

  /**
   * fig4 field in *S25252525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.fig4
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig4: prismic.RichTextField;

  /**
   * link4 field in *S25252525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s25252525.primary.link4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link4: prismic.LinkToMediaField;
}

/**
 * Default variation for S25252525 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S25252525SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<S25252525SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *S25252525*
 */
type S25252525SliceVariation = S25252525SliceDefault;

/**
 * S25252525 Shared Slice
 *
 * - **API ID**: `s25252525`
 * - **Description**: S25252525
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S25252525Slice = prismic.SharedSlice<
  "s25252525",
  S25252525SliceVariation
>;

/**
 * Primary content in *S3366 → Primary*
 */
export interface S3366SliceDefaultPrimary {
  /**
   * L33 field in *S3366 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.l33
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  l33: prismic.ImageField<never>;

  /**
   * title field in *S3366 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * year field in *S3366 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * fig field in *S3366 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;

  /**
   * 33link field in *S3366 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.33link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "33link": prismic.ContentRelationshipField;

  /**
   * 66link field in *S3366 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.66link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "66link": prismic.ContentRelationshipField;
}

/**
 * Primary content in *S3366 → Items*
 */
export interface S3366SliceDefaultItem {
  /**
   * R66 field in *S3366 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].r66
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  r66: prismic.ImageField<never>;

  /**
   * title field in *S3366 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * year field in *S3366 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * fig field in *S3366 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;
}

/**
 * Default variation for S3366 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S3366SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<S3366SliceDefaultPrimary>,
  Simplify<S3366SliceDefaultItem>
>;

/**
 * Primary content in *S3366 → Primary*
 */
export interface S3366SliceSwappedL66R33Primary {
  /**
   * L33 field in *S3366 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.l33
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  l33: prismic.ImageField<never>;

  /**
   * title field in *S3366 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * year field in *S3366 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * fig field in *S3366 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;

  /**
   * 33link field in *S3366 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.33link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "33link": prismic.ContentRelationshipField;

  /**
   * 66link field in *S3366 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.primary.66link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  "66link": prismic.ContentRelationshipField;
}

/**
 * Primary content in *S3366 → Items*
 */
export interface S3366SliceSwappedL66R33Item {
  /**
   * R66 field in *S3366 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].r66
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  r66: prismic.ImageField<never>;

  /**
   * title field in *S3366 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * year field in *S3366 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * fig field in *S3366 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s3366.items[].fig
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig: prismic.RichTextField;
}

/**
 * Swapped L66 R33 variation for S3366 Slice
 *
 * - **API ID**: `swappedL66R33`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S3366SliceSwappedL66R33 = prismic.SharedSliceVariation<
  "swappedL66R33",
  Simplify<S3366SliceSwappedL66R33Primary>,
  Simplify<S3366SliceSwappedL66R33Item>
>;

/**
 * Slice variation for *S3366*
 */
type S3366SliceVariation = S3366SliceDefault | S3366SliceSwappedL66R33;

/**
 * S3366 Shared Slice
 *
 * - **API ID**: `s3366`
 * - **Description**: S3366
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S3366Slice = prismic.SharedSlice<"s3366", S3366SliceVariation>;

/**
 * Primary content in *S404020 → Primary*
 */
export interface S404020SliceDefaultPrimary {
  /**
   * image401 field in *S404020 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.image401
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image401: prismic.ImageField<never>;

  /**
   * title401 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.title401
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title401: prismic.RichTextField;

  /**
   * year401 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.year401
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year401: prismic.RichTextField;

  /**
   * fig401 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.fig401
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig401: prismic.RichTextField;

  /**
   * link401 field in *S404020 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.link401
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link401: prismic.LinkToMediaField;

  /**
   * image402 field in *S404020 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.image402
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image402: prismic.ImageField<never>;

  /**
   * title402 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.title402
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title402: prismic.RichTextField;

  /**
   * year402 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.year402
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year402: prismic.RichTextField;

  /**
   * fig402 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.fig402
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig402: prismic.RichTextField;

  /**
   * link402 field in *S404020 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.link402
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link402: prismic.LinkToMediaField;

  /**
   * image20 field in *S404020 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.image20
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image20: prismic.ImageField<never>;

  /**
   * title20 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.title20
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title20: prismic.RichTextField;

  /**
   * year20 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.year20
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year20: prismic.RichTextField;

  /**
   * fig20 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.fig20
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig20: prismic.RichTextField;

  /**
   * link20 field in *S404020 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.link20
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link20: prismic.LinkToMediaField;
}

/**
 * Default variation for S404020 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S404020SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<S404020SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *S404020 → Primary*
 */
export interface S404020Slice402040Primary {
  /**
   * image401 field in *S404020 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.image401
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image401: prismic.ImageField<never>;

  /**
   * title401 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.title401
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title401: prismic.RichTextField;

  /**
   * year401 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.year401
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year401: prismic.RichTextField;

  /**
   * fig401 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.fig401
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig401: prismic.RichTextField;

  /**
   * link401 field in *S404020 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.link401
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link401: prismic.LinkToMediaField;

  /**
   * image20 field in *S404020 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.image20
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image20: prismic.ImageField<never>;

  /**
   * title20 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.title20
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title20: prismic.RichTextField;

  /**
   * year20 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.year20
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year20: prismic.RichTextField;

  /**
   * fig20 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.fig20
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig20: prismic.RichTextField;

  /**
   * link20 field in *S404020 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.link20
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link20: prismic.LinkToMediaField;

  /**
   * image402 field in *S404020 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.image402
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image402: prismic.ImageField<never>;

  /**
   * title402 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.title402
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title402: prismic.RichTextField;

  /**
   * year402 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.year402
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year402: prismic.RichTextField;

  /**
   * fig402 field in *S404020 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.fig402
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig402: prismic.RichTextField;

  /**
   * link402 field in *S404020 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s404020.primary.link402
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link402: prismic.LinkToMediaField;
}

/**
 * 402040 variation for S404020 Slice
 *
 * - **API ID**: `402040`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S404020Slice402040 = prismic.SharedSliceVariation<
  "402040",
  Simplify<S404020Slice402040Primary>,
  never
>;

/**
 * Slice variation for *S404020*
 */
type S404020SliceVariation = S404020SliceDefault | S404020Slice402040;

/**
 * S404020 Shared Slice
 *
 * - **API ID**: `s404020`
 * - **Description**: S404020
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S404020Slice = prismic.SharedSlice<
  "s404020",
  S404020SliceVariation
>;

/**
 * Primary content in *S5050 → Primary*
 */
export interface S5050SliceDefaultPrimary {
  /**
   * image1 field in *S5050 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * title1 field in *S5050 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * year1 field in *S5050 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.year1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year1: prismic.RichTextField;

  /**
   * fig1 field in *S5050 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.fig1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig1: prismic.RichTextField;

  /**
   * link1 field in *S5050 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkToMediaField;

  /**
   * link2 field in *S5050 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkToMediaField;
}

/**
 * Primary content in *S5050 → Items*
 */
export interface S5050SliceDefaultItem {
  /**
   * image2 field in *S5050 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * title2 field in *S5050 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].title2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * year2 field in *S5050 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].year2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year2: prismic.RichTextField;

  /**
   * fig2 field in *S5050 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].fig2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig2: prismic.RichTextField;
}

/**
 * Default variation for S5050 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S5050SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<S5050SliceDefaultPrimary>,
  Simplify<S5050SliceDefaultItem>
>;

/**
 * Primary content in *S5050 → Primary*
 */
export interface S5050SliceSliderOnTheLeftPrimary {
  /**
   * image1 field in *S5050 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * title1 field in *S5050 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * year1 field in *S5050 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.year1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year1: prismic.RichTextField;

  /**
   * fig1 field in *S5050 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.fig1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig1: prismic.RichTextField;

  /**
   * link1 field in *S5050 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkToMediaField;

  /**
   * link2 field in *S5050 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.primary.link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkToMediaField;
}

/**
 * Primary content in *S5050 → Items*
 */
export interface S5050SliceSliderOnTheLeftItem {
  /**
   * image2 field in *S5050 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * title2 field in *S5050 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].title2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * year2 field in *S5050 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].year2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year2: prismic.RichTextField;

  /**
   * fig2 field in *S5050 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s5050.items[].fig2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig2: prismic.RichTextField;
}

/**
 * Slider on the left variation for S5050 Slice
 *
 * - **API ID**: `sliderOnTheLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S5050SliceSliderOnTheLeft = prismic.SharedSliceVariation<
  "sliderOnTheLeft",
  Simplify<S5050SliceSliderOnTheLeftPrimary>,
  Simplify<S5050SliceSliderOnTheLeftItem>
>;

/**
 * Slice variation for *S5050*
 */
type S5050SliceVariation = S5050SliceDefault | S5050SliceSliderOnTheLeft;

/**
 * S5050 Shared Slice
 *
 * - **API ID**: `s5050`
 * - **Description**: S5050
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S5050Slice = prismic.SharedSlice<"s5050", S5050SliceVariation>;

/**
 * Primary content in *S7525 → Primary*
 */
export interface S7525SliceDefaultPrimary {
  /**
   * image25 field in *S7525 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * title25 field in *S7525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * year25 field in *S7525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.year1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year1: prismic.RichTextField;

  /**
   * fig25 field in *S7525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.fig1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig1: prismic.RichTextField;

  /**
   * link25 field in *S7525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkToMediaField;

  /**
   * link75 field in *S7525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkToMediaField;
}

/**
 * Primary content in *S7525 → Items*
 */
export interface S7525SliceDefaultItem {
  /**
   * image75 field in *S7525 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * title75 field in *S7525 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].title2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * year75 field in *S7525 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].year2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year2: prismic.RichTextField;

  /**
   * fig75 field in *S7525 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].fig2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig2: prismic.RichTextField;
}

/**
 * Default variation for S7525 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S7525SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<S7525SliceDefaultPrimary>,
  Simplify<S7525SliceDefaultItem>
>;

/**
 * Primary content in *S7525 → Primary*
 */
export interface S7525Slice75OnTheLeftPrimary {
  /**
   * image25 field in *S7525 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.image1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * title25 field in *S7525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.title1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * year25 field in *S7525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.year1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year1: prismic.RichTextField;

  /**
   * fig25 field in *S7525 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.fig1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig1: prismic.RichTextField;

  /**
   * link25 field in *S7525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.link1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link1: prismic.LinkToMediaField;

  /**
   * link75 field in *S7525 → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.primary.link2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link2: prismic.LinkToMediaField;
}

/**
 * Primary content in *S7525 → Items*
 */
export interface S7525Slice75OnTheLeftItem {
  /**
   * image75 field in *S7525 → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].image2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * title75 field in *S7525 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].title2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * year75 field in *S7525 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].year2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year2: prismic.RichTextField;

  /**
   * fig75 field in *S7525 → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: s7525.items[].fig2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fig2: prismic.RichTextField;
}

/**
 * 75 on the left variation for S7525 Slice
 *
 * - **API ID**: `75OnTheLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S7525Slice75OnTheLeft = prismic.SharedSliceVariation<
  "75OnTheLeft",
  Simplify<S7525Slice75OnTheLeftPrimary>,
  Simplify<S7525Slice75OnTheLeftItem>
>;

/**
 * Slice variation for *S7525*
 */
type S7525SliceVariation = S7525SliceDefault | S7525Slice75OnTheLeft;

/**
 * S7525 Shared Slice
 *
 * - **API ID**: `s7525`
 * - **Description**: S7525
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type S7525Slice = prismic.SharedSlice<"s7525", S7525SliceVariation>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Date field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;

  /**
   * Title field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Date field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;

  /**
   * Title field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *TextWithImage → Items*
 */
export interface TextWithImageSliceDefaultItem {
  /**
   * Image field in *TextWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *TextWithImage → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Text_on_top variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  Simplify<TextWithImageSliceDefaultItem>
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceTextOnTopPrimary {
  /**
   * Date field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;

  /**
   * Title field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *TextWithImage → Items*
 */
export interface TextWithImageSliceTextOnTopItem {
  /**
   * Image field in *TextWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *TextWithImage → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Image_on_top variation for TextWithImage Slice
 *
 * - **API ID**: `textOnTop`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceTextOnTop = prismic.SharedSliceVariation<
  "textOnTop",
  Simplify<TextWithImageSliceTextOnTopPrimary>,
  Simplify<TextWithImageSliceTextOnTopItem>
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceImageBetweenPrimary {
  /**
   * Date field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  date: prismic.RichTextField;

  /**
   * Title field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Text_bottom field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text_bottom
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_bottom: prismic.RichTextField;
}

/**
 * Primary content in *TextWithImage → Items*
 */
export interface TextWithImageSliceImageBetweenItem {
  /**
   * Image field in *TextWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *TextWithImage → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;
}

/**
 * Image_between variation for TextWithImage Slice
 *
 * - **API ID**: `imageBetween`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceImageBetween = prismic.SharedSliceVariation<
  "imageBetween",
  Simplify<TextWithImageSliceImageBetweenPrimary>,
  Simplify<TextWithImageSliceImageBetweenItem>
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceTextOnTop
  | TextWithImageSliceImageBetween;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SelectedProjectDocument,
      SelectedProjectDocumentData,
      SelectedProjectDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      FullwidthSlice,
      FullwidthSliceDefaultPrimary,
      FullwidthSliceDefaultItem,
      FullwidthSlicePaddingOnTheSidesItem,
      FullwidthSliceVariation,
      FullwidthSliceDefault,
      FullwidthSlicePaddingOnTheSides,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceDefaultItem,
      ImageSliceVariation,
      ImageSliceDefault,
      S25252525Slice,
      S25252525SliceDefaultPrimary,
      S25252525SliceVariation,
      S25252525SliceDefault,
      S3366Slice,
      S3366SliceDefaultPrimary,
      S3366SliceDefaultItem,
      S3366SliceSwappedL66R33Primary,
      S3366SliceSwappedL66R33Item,
      S3366SliceVariation,
      S3366SliceDefault,
      S3366SliceSwappedL66R33,
      S404020Slice,
      S404020SliceDefaultPrimary,
      S404020Slice402040Primary,
      S404020SliceVariation,
      S404020SliceDefault,
      S404020Slice402040,
      S5050Slice,
      S5050SliceDefaultPrimary,
      S5050SliceDefaultItem,
      S5050SliceSliderOnTheLeftPrimary,
      S5050SliceSliderOnTheLeftItem,
      S5050SliceVariation,
      S5050SliceDefault,
      S5050SliceSliderOnTheLeft,
      S7525Slice,
      S7525SliceDefaultPrimary,
      S7525SliceDefaultItem,
      S7525Slice75OnTheLeftPrimary,
      S7525Slice75OnTheLeftItem,
      S7525SliceVariation,
      S7525SliceDefault,
      S7525Slice75OnTheLeft,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceDefaultItem,
      TextWithImageSliceTextOnTopPrimary,
      TextWithImageSliceTextOnTopItem,
      TextWithImageSliceImageBetweenPrimary,
      TextWithImageSliceImageBetweenItem,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceTextOnTop,
      TextWithImageSliceImageBetween,
    };
  }
}
