// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  image: defineAsyncComponent(() => import("./Image/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
  text_with_image: defineAsyncComponent(
    () => import("./TextWithImage/index.vue")
  ),
});
